const BAD_REQUEST = 400;
const UNAUTH_ERROR = 401;
const NOT_FOUND = 404;
const CONFLICT_ERROR = 409;
const SERVER_ERROR = 500;

module.exports = {
  BAD_REQUEST,
  UNAUTH_ERROR,
  NOT_FOUND,
  CONFLICT_ERROR,
  SERVER_ERROR,
};
